### ISSUE TITLE
Espionage Suggestions and Discussion

### ISSUE THREAD

**Issue by the-s-is-silent** [SpacedOutChicken/Deciv-2#1]
So, it happened. *The* major missing G&K mechanic was finally added.

This will be a discussion for how espionage should be incorporated into this fork of DeCiv over the next few days (re: keeping it true to DeCiv flavor).

**Relevant Buildings and Wonders**
I propose converting the Listening Post into the Tier 1 anti-spy building and introducing a new building to function as the Great Person booster. My expansion mod "Outlaws of the Wastes" has already partially done this with its Community Garden building in its latest update, but I am interested in hearing any ideas the rest of the DeCiv community has here. If the Community Garden in Outlaws of the Wastes is ported over to this fork instead of making an entirely new building, some adjustments to other buildings that are unrelated to espionage might be made.

Additionally, Crimson Legion's Colosseum and Cult of Ignis' Arena UBs would be altered so that they replace the Stadium instead of the Listening Post and they would receive additional UBs to serve as their new Listening Post replacements. (I have no clue what Ignis' new Listening Post replacement might be called or even if there's a possible lore-accurate one to add. Legion's is easy, though: Frumentarii Camp.)

My proposed name for the Tier 2 anti-spy building would be the Field Office, which would be identical stat-wise to G&K's Police Station, and the connected National Wonder would be called the National Security Service which would also be identical stat-wise to G&K's National Intelligence Agency; the only differences being the techs that unlock them.

I do not yet have a proposal for a Great Firewall equivalent for DeCiv.

There also needs to be a question raised: should the Listening Post keep its other effect of eliminating extra unhappiness from annexed cities or not? If not, should the Prison Camp be reworked?

**Spy Names**
At present, I only have possible spy name lists for seven of the fourteen factions in the current iteration of DeCiv Redux and will be counting on others to create flavor-accurate spy name lists for the others, as well as to revise the name lists I currently have.

- Atlas' proposed spy name list borrows the names of characters from its source material, *Atlas Shrugged*. The list: "Dagny", "Rearden", "Wyatt", "Akston", "Danagger", "Midas", "Kay", "Quentin", "Halley", "Allen".
- Blackwarden's proposed spy name list is based on various executive officers and other important employees of the PMC formerly known as Blackwater. The list: "Al", "Cofer", "Richer", "Ashcroft", "Quinn", "Bonfiglio", "Danielle", "Inman", "Robinson", "Folsom".
- Crimson Legion's proposed spy name list borrows the spy name list for the Caesar's Legion mod for official Civ 5, with some adjustments to also include from the cancelled *Van Buren* and a certain *Honest Hearts* mod for *New Vegas*. The list: "Vulpes", "Cato", "Alerio", "Caius", "Ulysses", "Silus", "Picus", "Aurelius", "Severus", "Livius".
- Cult of Ignis' proposed spy name list borrows the names of various antagonists from the *Mad Max* franchise, half of them being from Immortan Joe's War Boys. The list: "Rictus", "Scabrous", "Rizzdale", "Fang", "Smeg", "Nux", "Slit", "Morsov", "Wez", "Zanetti".
- The Mariners' proposed spy name list can only use characters from *Waterworld*. (Considering the city list naming theme for the faction uses the names of the actors + actresses, this is duly given.) The list: "Enola", "Gregor", "Sawzall", "Priam", "Bone", "Toby", "Smitty", "Djeng", "Truan", "Ledger".
- New Star's proposed spy name list... I decided to have a little fun with this one. Going off the updated faction lore for the planned Rebirth Edition update, I decided to use a variety of fictional characters whose last names are all Starling. The list: "Henry", "Jim", "Clarice", "Juliet", "Ashlee", "Robyn", "Ben", "Jodie", "Harvey", "Juno".
- Proklyatyye's proposed spy name list borrows from *Roadside Picnic* and two of the works it inspired: *S.T.A.L.K.E.R.* and *Metro 2033*. The list: "Redrick", "Victor", "Artyom", "Kirill", "Dr. Kruglov", "Mr. Strugatsky", "Vitalik", "Lebedev", "Letyaga", "Mirsky".

Of the unaddressed factions, Enclavers should be easiest to figure out (notable survivalists in either real life or fiction), followed by New Afrika (no clear theme stands out, but stick to male African names you'd expect to find in Mali, Ethiopia, and also over on this side of the Pacific in Jamaica and it should be fine). Rust, Commonwealth and Patriots will be the hard ones.

**Timing of Unlocking Spies**
Let's be honest: this is going to be a mess. In official Civ 5, the first spies for everyone are gained once any civilization reaches the Renaissance era. In the current version of DeCiv, four of the mod's fourteen factions have starting techs that automatically put them in its equivalent era, the Rebuilding era. Do those factions need to be adjusted so that they are kicked out of the Rebuilding era? Does the tech tree need to be adjusted? Or will the "simple" solution (which doesn't fix enough) merely be to have the first spies unlock at the Industrial era so shenanigans don't occur in games where any of the relevant factions (Atlas, Blackwarden, Hexlock, Patriots) spawn?

Edit 1: Added Ignis and Mariner spy names.
Edit 2: Added Blackwarden spy names.
Edit 3: Another tidbit on Legion/Ignis regarding their Listening Post replacements.
Edit 4: Another tidbit on the missing factions' spy names.

**Comment by SpacedOutChicken** [comment]
For Hexlock spy names, I suggest using names of notable robots and artificial intelligences (Claude, Eliza, Watson, Kismet, Asimo, Bert, Neil, Blue, Alice, Alpha). For Deadrock Clan spy names, I suggest using famous gangster names (Capone, Escobar, Dillinger, Kray, Luciano, Bulger, Gotti, Siegel, Gambino, Cassidy).

To address the big question first: the core of the problem appears to be the inclusion of Electronics as a starting tech. I'm not sure that giving that as a starting tech was ever a good idea. Remove that, and we might solve multiple problems. We just need to figure out something else to reflect the idea that these factions managed to preserve some tech during the great collapse.

As for some of the buildings, I like the fact that the Listening Post and the Prison Camp are mutually exclusive. As I see it, when you conquer a city, you can choose to either set up a good spy network or set up an iron-fisted prison system, but you can't do both because your resources are limited. Do you think that's reasonable, or am I off base?

We also need to address policies, and to that end, I have an idea. While some policies should definitely make you more resistant to spying, could some policies make you more vulnerable? DeCiv's policies are full of tradeoffs like that, and I can see some policies and cultural practices making a civilization more vulnerable to espionage. One of the factions in Alpha Centauri, University of Planet, has this weakness: they're better at science, but it's easier to steal tech from them because of their general practice of open sharing of ideas. Could Rationalism have this weakness?

Edit 1: Added more spy names

Edit 2: On second thought, for Deadrock Clan spy names, it might be better to use gangster nicknames. New suggestions: Bugsy, Whitey, Soapy, Mickey, Baby Face, Ducks, Chin, Bomp, Owney, Lilo.

Edit 3: Added faction name.

**Comment by the-s-is-silent** [comment]
You're pretty much on point with the rationale for keeping the Listening Post and Prison Camp mutually exclusive. I'm not sure about Rationalism increasing spy vulnerability here due to some of the current policy names and the negative connotations regarding freedom of information that may be connected to them, but considering how overpowered the tree is...

My first thought for Deadrock spy names was something similar, but starting with notable Indonesian criminals (mostly due to Sullien's planned rework of the faction), but yours works better.

With Electronics being eliminated from the starting tech list for everyone, this would also be high time to fix the mess that is the Difficulties.json and Eras.json files and make later era game starts actually matter when you're not using Sandbox difficulty to test things.

**Comment by SpacedOutChicken** [comment]
If Rationalism is overpowered, then having it be "leaky" seems like a good way to balance it out. Now we just need to make a policy with that side effect. I'm open to making big changes to all the policy branches, and not just for accommodating espionage.

**Comment by the-s-is-silent** [comment]
From Indonesian Gentleman on the Discord server:

"Also, in the light of future espionage mechanics - I think having Deadrock be a spy nation works
As in, we can add espionage mechanics to Deadrock and they'd fit quite nicely"

🤔

**Comment by SpacedOutChicken** [comment]
I propose dropping Deadrock Clan's ability to recruit barbarians from camps (leave that ability to Crimson Legion) and giving Deadrock extra spies and spy resistance, because snitches get stitches.

**Comment by SpacedOutChicken** [comment]
For the Patriots, I propose using names from Tom Clancy novels (Ryan, Fisher, Ding, Hansen, Briggs) and Clive Cussler novels (Dirk, Kurt, Isaac, Dorn, Remi). I think that these books reflect the self-image that the Patriots would cultivate.

Edit: Added all ten names

**Comment by SpacedOutChicken** [comment]
Proposed New Afrika names: Mumia, Ashanti, Sundiata, Kuwasi, Dhoruba, Safiya, Kwaku, Kom'boa, Bashir, Jamal. All names of notable Black Panther Party members.

**Comment by the-s-is-silent** [comment]
I'm missing two for Enclavers right now (and expect further revisions to what I have so far). The theme I went with was notable survivalists in fiction, using the characters' last names. Gummer (*Tremors* - you can't *not* give *Tremors* a shout-out here), Krantz (the titular *Postman*), Cawdor (*Deathlands*), Neville (*I Am Legend*), Eli (*The Book of Eli*), Quinelle (*The Survivors*), Rouke (*The Survivalist* - 1980s novel, *not* the 2015 movie), and Redeker (the character who came up with the plan to defeat the Zombie Apocalypse in *World War Z*).

**Comment by SpacedOutChicken** [comment]
Two more survivalists: Verney (from Mary Shelley's _The Last Man_) and Brown (from Vertigo Comics' _Y: The Last Man_).

**Comment by the-s-is-silent** [comment]
Not posting them here (at least not yet), but I have a preliminary spy name list for Children of Rust now (going off Indonesian Gentleman's suggested "stereotypical Native American naming theme"). That just leaves the Commonwealth's spy names (and maybe a new Listening Post replacement for Ignis) and then that branch can be pushed.

**Comment by SpacedOutChicken** [comment]
For the Commonwealth, I propose names from prominent members of the French, German, and Italian resistance to the Nazis: Jean, Pascal, Henri, Otto, Elise, Heinrich, Dietrich, Ivanoe, Pietro, Ugo.

**Comment by SpacedOutChicken** [comment]
For a national wonder related to espionage, I propose the Information Awareness Office, unlocked at Electronics. Its function would be similar to Unciv's National Intelligence Agency: promoting all spies and granting a new one. It could require a certain building to be built in all cities, but I'm not sure what that should be. It shouldn't be the Listening Post, since that building may not be built in some occupied cities. 

For a world wonder, I propose the Virtual Panopticon, unlocked at Computers. This would be roughly equivalent to the Great Firewall. It could also reduce unhappiness, reflecting its ability to suppress dissent.

**Comment by the-s-is-silent** [comment]
I would have the Information Awareness Office be unlocked later at Networking, and the Virtual Panopticon pushed back to Social Engineering. Also, I'd already suggested a name for the Tier 2 anti-spy building that it would need back in the first post (Field Office, as in a federal law enforcement/security service field office akin to the FBI and USSS), though as for when it'd unlock, the best/most fitting tech I could think of was Combined Arms (and no, it shouldn't unlock in the Rebuilding era).

**Comment by SpacedOutChicken** [comment]
Sorry for overlooking the Field Office suggestion. Anyways, I approve of your counter proposal. Let's do that.
