### ISSUE TITLE
Fixing the factions: Deadrock Clan

### ISSUE THREAD

**Issue by SpacedOutChicken** [SpacedOutChicken/Deciv-2#4]
With espionage now being a thing, we need to make a few other changes, and I want to start with changing the Deadrock Clan, our favorite organized crime syndicate. They deserve to have some spy stuff as part of their unique abilities, and I think they could use some other fixes as well. Some ideas to consider:

* Giving them an extra spy seems like an easy call. I think they should also have some spy resistance, and I suggest that we tie it to a building. Having the Clubhouse grant localized spy resistance, perhaps of -15%, feels right to me.
* With espionage being their new shtick, we should remove some other unique abilities. The unique of quickly recovering city-state influence no longer seems necessary since they can use spies to rig elections. Let Blackwarden keep that one for themselves. The unique of recruiting barbarians also seems like a bad fit. Leave that one to Crimson Legion. 
* That said, without recruiting barbarians, Deadrock could be at a major disadvantage because they are currently highly dependent on having slaves in order to build military units. I think that we should reduce their dependence on slavery.

Those are my opening thoughts. What do you all say? How can we modernize the Deadrock Clan?

**Comment by the-s-is-silent** [comment]
I will point out that Deadrock Clan has already been modified in some of the ways asked about here, namely, swapping out the Barbarian recruitment in the UA for the extra spy resistance (the current 25% is probably a bit too high, though) + extra spy on reaching the Rebuilding era.

I will also note that my expansion mod chose to handle the Slave resource dependence by buffing Shake Down Survivors (4 vs. base Deciv's 2 + grant a free Gangboss, and Prison farm GI also buffed to make it actually worth placing, but jacked up Production cost appropriately) + creating a new Prison Camp replacement, while also giving them one of Ignis' UBs. But this opens up the can of worms that is copying too much from that mod. However, ATM they won't really be actually building Enslaved units much anyway since those units are so badly inferior to Weapons units (and even to other Low Tech units sometimes) that what even is the point? But anyway, my suggestion is that rather than reduce Slave dependence, Deadrock should embrace it and make it so they have enough to pay for both the buildings that need slaves and still be able to train units that need the same (and make sure those units are worth training).

**Comment by SpacedOutChicken** [comment]
Sorry for not noticing the changes to Deadrock. That was rather stupid of me.

My own ignorance aside, I'm actually okay with copying good ideas from expansion mods like yours. If it's good enough for an expansion, then maybe it's good enough for the original as well.
